language: cpp
sudo: false
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    compiler: clang
    env: CXX=clang++

before_install:
- brew outdated cmake || brew upgrade cmake

script:
- cd build
- cmake ..
- make
- test/Test
