language: cpp
sudo: false
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    compiler: clang
    env: COMPILER=clang++
  - os: osx
    osx_image: xcode9.4
    compiler: gcc
    install:
    - brew install gcc
    - brew link --overwrite gcc
    env: COMPILER=g++8
  - os: osx
    osx_image: xcode9
    compiler: clang
    env: COMPILER=clang++
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test"]
        packages: ["g++-7"]
    env: COMPILER=g++-7
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test"]
        packages: ["g++-7"]
    env:
      - COMPILER=g++-7
      - CXXFLAGS="-DNDEBUG -O0 --coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
    before_script:
      - pip install --user cpp-coveralls
    after_success:
      - coveralls --gcov gcov-7 --gcov-options '\-lp' --root ${TRAVIS_BUILD_DIR} --build-root ${TRAVIS_BUILD_DIR}/build -e Examples -e test -e CLI --extension cpp --extension hpp -i src -i include

before_script:
- export CXX=${COMPILER}

script:
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug ..
- make
- test/suite
