language: cpp
sudo: false
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    compiler: clang
    env: COMPILER=clang++
  - os: osx
    osx_image: xcode9
    compiler: clang
    env: COMPILER=clang++
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test"]
        packages: ["g++-7"]
    env: COMPILER=g++-7
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test"]
        packages: ["g++-7"]
    env:
      - COMPILER=g++-7
      - CXXFLAGS="-O0 --coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
    before_script:
      - pip install --user cpp-coveralls
    after_success:
      - coveralls --gcov gcov-7 --gcov-options '\-lp' --root ${TRAVIS_BUILD_DIR} --build-root ${TRAVIS_BUILD_DIR}/build -e Examples -e test -e CLI -E .+CMakeCXXCompilerId\.cpp --extension cpp --extension hpp -i src -i include

  # #include <string_view> fails
  # - os: linux
  #   compiler: clang
  #   addons:
  #     apt:
  #       sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"]
  #       packages: ["clang-5.0", "libstdc++-4.9-dev"]
  #   env:
  #   - COMPILER=clang++-5.0
  #   - CXXFLAGS="-stdlib=libstdc++"

before_install:
- export CXX=${COMPILER}

script:
- cd build
- cmake ..
- make
- test/suite
